#!/usr/bin/env python3
"""
Turn data/dictionary.json into the compact lexicon the web app loads.

The app is a single static page that must also work when opened straight from
disk (file://), where fetch() is blocked. So the lexicon ships as a plain
<script> file assigning one global, not as JSON fetched at runtime.

Rows are arrays rather than objects to keep the file small:

    [beary, ascii, english, pos, seeAlso]

      beary    Roman transliteration exactly as printed in the Lexicon
      ascii    same word with diacritics folded away, for typing and search
      english  the English gloss, verbatim
      pos      "n" noun, "v" verb, "" not marked in the source
      seeAlso  variant forms, omitted when there are none

Usage:  python3 tools/build_lexicon.py
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "data", "dictionary.json")
OUT = os.path.join(ROOT, "lexicon_data.js")

POS_CODE = {"noun": "n", "verb": "v", "": ""}

HEADER = """\
// Beary <-> English lexicon, generated by tools/build_lexicon.py -- do not edit.
//
// Source: Beary-Kannada-English Lexicon ("Nigantu"), Karnataka Beary Sahitya
// Academy, 2017. Editors B.M. Ichlangod, B.A. Shamshuddin Madikeri and Abdul
// Rahman Kuthethoor; English glosses by Prof. B. Surendra Rao.
//
// Row format: [beary, ascii, english, pos, seeAlso?]
// %(count)d entries.
"""


def main():
    with open(SRC, encoding="utf-8") as fh:
        entries = json.load(fh)

    rows = []
    for e in entries:
        row = [e["beary"], e["beary_ascii"], e["english"],
               POS_CODE.get(e["pos"], "")]
        if e.get("see_also"):
            row.append(e["see_also"])
        rows.append(row)

    body = ",\n".join(json.dumps(r, ensure_ascii=False) for r in rows)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER % {"count": len(rows)})
        fh.write("const BEARY_LEXICON = [\n")
        fh.write(body)
        fh.write("\n];\n")

    size = os.path.getsize(OUT)
    print(f"Wrote {len(rows)} entries -> {OUT}  ({size/1024/1024:.2f} MB)")


if __name__ == "__main__":
    main()
