#!/usr/bin/env python3
"""
Turn data/dictionary.json into the compact lexicon the web app loads.

The app is a single static page that must also work when opened straight from
disk (file://), where fetch() is blocked. So the lexicon ships as a plain
<script> file assigning one global, not as JSON fetched at runtime.

Rows are arrays rather than objects to keep the file small:

    [beary, ascii, english, pos, seeAlso]

      beary    Roman transliteration exactly as printed in the Lexicon
      ascii    same word with diacritics folded away, for typing and search.
               Where the Lexicon brackets a variant -- "añci(cɛ)" means añci or
               añcɛ -- every spelling a user might type is included, separated
               by "|", so both reach the entry.
      english  the English gloss, verbatim
      pos      "n" noun, "v" verb, "" not marked in the source
      seeAlso  variant forms, omitted when there are none

Usage:  python3 tools/build_lexicon.py
"""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_dictionary import fold_ascii  # noqa: E402  (same folding rules)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "data", "dictionary.json")
OUT = os.path.join(ROOT, "lexicon_data.js")

POS_CODE = {"noun": "n", "verb": "v", "": ""}

# --- the ḍo / ro dialect alternation -------------------------------------
# The genitive and verbal-noun suffix is -ro around Mangalore city and Ullal,
# -ḍo further north around Udupi. Same suffix, different region.
#
# It only alternates after a vowel. After a nasal, ro is impossible and both
# varieties say ḍo -- which is why "n'aṇḍo" (my) is never "n'aṇro". The Lexicon
# bears this out with no exceptions: all 980 alternations it brackets as
# "ḍo(ro)" follow a vowel, and of 159 words ending in -ro not one follows a
# nasal.
VOWELS = "aāiīuūụeēɛoō"
BRACKETED = re.compile(r"ḍ([oɛe])\(r([oɛe])\)")
BARE_DO = re.compile(f"([{VOWELS}])ḍ([oɛe])$")
BARE_RO = re.compile(f"([{VOWELS}])r([oɛe])$")


def to_dialect(word, south=True):
    """Render a Lexicon headword in one variety or the other."""
    word = BRACKETED.sub(
        (lambda m: "r" + m.group(2)) if south else (lambda m: "ḍ" + m.group(1)),
        word)
    if south:
        return BARE_DO.sub(r"\1r\2", word)
    return BARE_RO.sub(r"\1ḍ\2", word)

HEADER = """\
// Beary <-> English lexicon, generated by tools/build_lexicon.py -- do not edit.
//
// Source: Beary-Kannada-English Lexicon ("Nigantu"), Karnataka Beary Sahitya
// Academy, 2017. Editors B.M. Ichlangod, B.A. Shamshuddin Madikeri and Abdul
// Rahman Kuthethoor; English glosses by Prof. B. Surendra Rao.
//
// Row format: [beary, ascii, english, pos, seeAlso?]
// %(count)d entries.
"""


def main():
    with open(SRC, encoding="utf-8") as fh:
        entries = json.load(fh)

    rows = []
    for e in entries:
        keys = list(e.get("ascii_variants") or [e["beary_ascii"]])
        # Someone typing the southern spelling must reach a headword printed in
        # the northern one, and the other way round.
        for base in (e.get("variants") or [e["beary"]]):
            for form in (to_dialect(base, True), to_dialect(base, False)):
                k = fold_ascii(form)
                if k and k not in keys:
                    keys.append(k)
        row = [e["beary"], "|".join(keys), e["english"],
               POS_CODE.get(e["pos"], "")]
        if e.get("see_also"):
            row.append(e["see_also"])
        rows.append(row)

    body = ",\n".join(json.dumps(r, ensure_ascii=False) for r in rows)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER % {"count": len(rows)})
        fh.write("const BEARY_LEXICON = [\n")
        fh.write(body)
        fh.write("\n];\n")

    size = os.path.getsize(OUT)
    print(f"Wrote {len(rows)} entries -> {OUT}  ({size/1024/1024:.2f} MB)")


if __name__ == "__main__":
    main()
